base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name="home"),
    path('calculate/<str:start>/',views.calc,name="calculate"),
    path('credits/', views.credits, name="credits")
]

tedwards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
]

base/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms
from django.core.exceptions import ValidationError

class adp_form(forms.Form):
    opt_choices = (
    ('1', "Twisted Edwards"),
    ('2', "Short Weirstrass"),
    ('3', "Montgomery")
    )
    opt = forms.ChoiceField(choices = opt_choices)
    a = forms.IntegerField(min_value=2,label='a')
    d = forms.IntegerField(min_value=1,label='d')
    p = forms.IntegerField(min_value=3,label='p')

    def clean_d(self):
        a = self.cleaned_data['a']
        d = self.cleaned_data['d']
        if a == d:
            raise ValidationError("Values of a and d cannot be equal!")
        return d

class opt_form(forms.Form):
    opt_choices = (
    ('2', "Addition (+)"),
    ('3', "Subtraction (-)"),
    ('4', "Doubling (x2)"),
    ('5', "Scalar Multiplication (xScalar)"),
    )
    opt = forms.ChoiceField(choices = opt_choices)
    x1 = forms.IntegerField()
    y1 = forms.IntegerField()
    x2 = forms.IntegerField(required=False)
    y2 = forms.IntegerField(required=False)

    def clean_x2(self):
        opt = self.cleaned_data['opt']
        x2 = self.cleaned_data['x2']
        if (opt == '2' or opt == '3' or opt == '5') and x2 == None:
            raise ValidationError("x2: Value required!")
        return x2
    
    def clean_y2(self):
        opt = self.cleaned_data['opt']
        y2 = self.cleaned_data['y2']
        if (opt == '2' or opt == '3') and y2 == None:
            raise ValidationError("y2: Value required!")
        return y2

base/views.py
from django import forms
from django.shortcuts import render
from base import forms
from base.curves import *
from sympy import nextprime
import math

# Create your views here.
# a = 0
# d = 0
# p = 0
# new_p = 0
# set = False

def home(request):
    # global a,d,p,new_p,set
    new_p = 0
    prime = 0
    
    adp_form = forms.adp_form()

    if request.method == "POST":

        adp_form = forms.adp_form(request.POST)

        if adp_form.is_valid():
            
            opt = request.session['opt'] = adp_form.cleaned_data['opt']
            a = request.session['a'] = adp_form.cleaned_data['a']
            d = request.session['d'] = adp_form.cleaned_data['d']
            p = request.session['p'] = adp_form.cleaned_data['p']
            request.session['set'] = True
            new_p = request.session['new_p'] = nextprime(p-1)
            lo = request.session['lo'] = int(new_p + 1 - 2*(new_p**0.5))
            hi = request.session['hi'] = int(new_p + 1 + 2*(new_p**0.5))
            prime = (new_p == p)

            #deciding on labels        
            a_label = 'a'
            d_label = 'd'
            p_label = 'p'

            if opt == '3':              
              a_label = 'A'
              d_label = 'B'
                        
            return render(request, 'base/home.html', {'adp_form': adp_form, 'stage': 2, 'a': a, 'd': d, 'p': p, 'new_p': new_p, 'lo': lo, 'hi': hi, 'prime': prime, 'a_label': a_label, 'd_label': d_label, 'p_label': p_label})
    return render(request, 'base/home.html', {'adp_form': adp_form, 'stage': 1})

def calc(request, start=0):
    # handle start value
    start = int(start)

    # global a,d,p,new_p,set
    if not request.session['set']:
        return render(request,'base/notset.html')
    else:
        curve = t_edwards
        opt1 = request.session['opt']
        # print("views -> opt1", opt1)

        a = request.session['a']
        d = request.session['d']
        new_p = request.session['new_p']
        curve = t_edwards
        if opt1 == '1':
            curve = t_edwards
        elif opt1 == '2':
            curve = s_weirstrass_curve
        elif opt1 == '3':
            curve = montgomery_curve
        points = curve.generatePoints(a, d, new_p, start)
        opt_form = forms.opt_form()

        a_label = 'a'
        d_label = 'd'
        p_label = 'p'
        
        if opt1 == '3':              
          a_label = 'A'
          d_label = 'B'
        
        # Operations +,-,* trigger POST
        if request.method == "POST":

            opt_form = forms.opt_form(request.POST)
            
            if opt_form.is_valid():

                opt = opt_form.cleaned_data['opt']
                x1 = opt_form.cleaned_data['x1']
                y1 = opt_form.cleaned_data['y1']
                x2 = opt_form.cleaned_data['x2']
                y2 = opt_form.cleaned_data['y2']

                # print(x1,y1,x2,y2)

                x_res = 0
                y_res = 0

                if(opt == '2'):
                    (x_res,y_res) = curve.addpoints(a,d,new_p,(x1,y1), (x2,y2))
                elif(opt == '3'):
                    (x_res,y_res) = curve.substractpoints(a,d,new_p,(x1,y1), (x2,y2))
                elif(opt == '4'):
                    (x_res,y_res) = curve.doublepoint(a,d,new_p,(x1,y1))
                elif(opt == '5'):
                    (x_res,y_res) = curve.multiplypoint(a,d,new_p,(x1,y1), x2)

                return render(request,'base/calculate.html',{'opt_form': opt_form, 'a': a, 'd': d, 'p': new_p, 'xarray': points[0], 'yarray': points[1], 'Array': zip(points[0], points[1]), 'point_count': len(points[0]), 'x_res': x_res, 'y_res': y_res, 'result': True, 'start': start, 'end': min(new_p-1, start+999), 'prev': max(0, start-1000), 'next': min(new_p-1, start+1000), 'p_minus_1': new_p-1,'curve': opt1, 'a_label': a_label, 'd_label': d_label, 'p_label': p_label})

        # GET
        return render(request,'base/calculate.html',{'opt_form': opt_form, 'a': a, 'd': d, 'p': new_p, 'xarray': points[0], 'yarray': points[1], 'Array': zip(points[0], points[1]), 'point_count': len(points[0]), 'start': start, 'end': min(new_p-1, start+999), 'prev': max(0, start-1000), 'next': min(new_p-1, start+1000), 'p_minus_1': new_p-1,'curve': opt1, 'a_label': a_label, 'd_label': d_label, 'p_label': p_label})
    
def credits(request):
    return render(request, 'base/credits.html')

templates/base/credits.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Elliptic Calculator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous"
    />

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <!-- Bootstrap JS -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"
    ></script>

    <!-- Google Font CDN -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Ubuntu&display=swap" rel="stylesheet">

    <!-- Pyplot CDN -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script async src="/cdn-cgi/bm/cv/669835187/api.js"></script>
    <style>
        .points-div {
        background-color: lightgrey;
        border: 2px solid black;
        overflow-y: scroll;
        overflow-x: hidden;
        max-height: 30vh;
        }

        #title{
        font-family: 'Ubuntu', sans-serif;
        }

        * {
        font-family: 'Noto Sans JP', sans-serif;
        }
    </style>

    <!-- footer styles -->
    <style>
        @media only screen and (max-width: 991.5px) {
        footer{
            font-size: small
        }
        }
        @media only screen and (max-width: 456px) {
        footer{
            font-size: 0.7em
        }
        }
        @media only screen and (max-width: 380px) {
        footer{
            font-size: 0.6em
        }
        }

        html,
        body {
        height: 100%;
        margin: 0;
        }
        .wrapper {
        min-height: 100%;

        /* Equal to height of footer */
        /* But also accounting for potential margin-bottom of last child */
        margin-bottom: -230px;
        }
        .footer_css_tricks,
        .push {
        height: 260px;
        }

        hr {
        border: 0;
        height: 1px;
        background-image: linear-gradient(
            to right,
            rgba(0, 0, 0, 0),
            rgba(0, 0, 0, 0.75),
            rgba(0, 0, 0, 0)
        );
        }
    </style>
</head>
<body class="bg-light">
    <div class="container bg-white py-3 shadow rounded wrapper">
        <h1 id="title" class="text-center mb-5">
            Contributors
        </h1>
        <ul>
            <li class="text-muted">
                [Montgomery Curve Implementation, Refactoring Web Interface] :
                <ul>
                  <li>
                    Suman Mondal
                    <a href="mailto: mondalsuman2001s@gmail.com"
                        >mondalsuman2001s@gmail.com</a
                    >
                  </li>
                  <li>
                    Sandip Maity
                    <a href="mailto: sandip1999maity@gmail.com"
                        >sandip1999maity@gmail.com</a
                    >
                  </li>
                  <li>
                    Sagnik Haldar
                    <a href="mailto: sagnikh2@gmail.com">sagnikh2@gmail.com</a>
                  </li>
                </ul>
            </li>
            <br />
            <li class="text-muted">
                [Twisted Edwards Curve Implementation, Web Interface] : 
                <ul>
                  <li>
                    Aditya Saha
                    <a href="mailto: adityacont@gmail.com">adityacont@gmail.com</a>
                  </li>
                  <li>
                    Ayan Ghosal
                    <a href="mailto: ayan.ghosal007@gmail.com">ayan.ghosal007@gmail.com</a>
                  </li>
                </ul>
            </li>
            <br />
            <li class="text-muted">
                [Short Weirstrass Curve Implementation] : 
                <ul>
                  <li>
                    Gargi Ghosal
                    <a href="mailto: ghosalgargi762@gmail.com">ghosalgargi762@gmail.com</a>
                  </li>
                  <li>
                    Agni Saha
                    <a href="mailto: agnisaha7799@gmail.com">agnisaha7799@gmail.com</a>
                  </li>
                </ul>
            </li>
            <br />
        </ul>
    </div>
</body>
</html>

templates/base/footer.html
<footer class="footer_css_tricks">
    <div class="container text-center fst-italic">
      <hr class="mb-xl-5" />
      <span class="text-muted">UG Final Year Project Work @2023 </span>
      <!-- <br /> -->
      <span class="text-muted"
        >Jadavpur University, Department of Information Technology,
        Kolkata</span
      >
      <br />
      <span class="text-muted">Developed By : </span>
      <a href="/credits" target="_blank">Click here to see the full list!</a>
      <br />
      <span class="text-muted"
        >Under the guidance of Prof. Utpal Kumar Ray
        <a href="mailto: utpal.ray@jadavpuruniversity.in"
          >utpal.ray@jadavpuruniversity.in</a
        >
        <!-- <br /> -->
        , Mentorship of Mr Sujay Kumar Paul
        <a href="mailto: sujaykumarpaul@gmail.com"
          >sujaykumarpaul@gmail.com</a
        >
      </span>
    </div>
  </footer>

templates/base/home.html
<!DOCTYPE html>
<html>
  <head>
    <title>Elliptic Calculator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <!-- Bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>

    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
    />

    <!-- MathJax CDN -->
    <script
      type="text/javascript"
      async
      src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"
    ></script>

    <!-- Google Font CDN -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Ubuntu&display=swap"
      rel="stylesheet"
    />

    <style>
      #title {
        font-family: "Ubuntu", sans-serif;
      }
      * {
        font-family: "Noto Sans JP", sans-serif;
      }

      input {
        min-width: 150px;
      }
    </style>
    <!-- footer styles -->
    <style>
      @media only screen and (max-width: 991.5px) {
        footer {
          font-size: small;
        }
      }
      @media only screen and (max-width: 456px) {
        footer {
          font-size: 0.7em;
        }
      }
      @media only screen and (max-width: 380px) {
        footer {
          font-size: 0.6em;
        }
      }

      html,
      body {
        height: 100%;
        margin: 0;
      }
      .wrapper {
        min-height: 100%;

        /* Equal to height of footer */
        /* But also accounting for potential margin-bottom of last child */
        margin-bottom: -230px;
      }
      .footer_css_tricks,
      .push {
        height: 260px;
      }

      hr {
        border: 0;
        height: 1px;
        background-image: linear-gradient(
          to right,
          rgba(0, 0, 0, 0),
          rgba(0, 0, 0, 0.75),
          rgba(0, 0, 0, 0)
        );
      }
    </style>
  </head>
  <body class="bg-light">
    <div class="container bg-white py-3 shadow rounded wrapper">
      <h1 id="title" class="text-center mb-5">
        Elliptic Curve Calculator over Finite Field
      </h1>
      
      <form class="mb-3 row" method="post">
        {% csrf_token %}
        <div class="col-12">
        <div class="input-group mb-3">
            <label class="input-group-text" for="id_opt">Select Curve:</label>
            {{ adp_form.opt }}
        </div>
        </div>

        <p id="equation1">
        Equation of Twisted Edwards Curve over finite field: $$y² = \frac{ax²
        -1}{dx² - 1} \hspace{3mm}mod \hspace{1mm}p$$
        </p>
        <p id="equation2" style="display: none;">
        Equation of Short Weirstrass Curve over finite field: $$y² = x³ + ax + d
        \hspace{3mm}mod \hspace{1mm}p$$
        </p>
        <p id="equation3" style="display: none;">
        Equation of Montgomery Curve over finite field: $$By² = x³ + Ax² + x
        \hspace{3mm}mod \hspace{1mm}p$$
        </p>
        <p class="mb-1 fw-bolder">User Input</p>
        <p class="mt-1">Please enter the parameters of the curve :</p>

        <div class="col-12 col-sm-4 col-md-3 col-xl-2">
          <div class="input-group mb-3">
            <label class="input-group-text" for="id_a">a:</label>
            {{ adp_form.a }}
          </div>
        </div>

        <div class="col-12 col-sm-4 col-md-3 col-xl-2">
          <div class="input-group mb-3">
            <label class="input-group-text" for="id_d">d:</label>
            {{ adp_form.d }}
          </div>
        </div>
        <div class="col-12 col-sm-4 col-md-3 col-xl-2">
          <div class="input-group mb-3">
            <label class="input-group-text" for="id_p">p:</label>
            {{ adp_form.p }}
          </div>
        </div>
        <h5 class="text-danger">{{ adp_form.a.errors }}</h5>
        <h5 class="text-danger">{{ adp_form.d.errors }}</h5>
        <h5 class="text-danger">{{ adp_form.p.errors }}</h5>

        <div class="col-12">
          <button type="submit" class="btn btn-secondary">Proceed</button>
        </div>
      </form>

      {% if stage == 2 %}
      <div
        id="msg-box"
        class="alert alert-warning alert-dismissible fade show"
        role="alert"
      >
        {% if prime %} {{a_label}} = {{a}}, {{d_label}} = {{d}}, {{p_label}} = {{p}}, continue with these
        values? {% else %} {{a_label}} = {{a}}, {{d_label}} = {{d}},
        <strong>{{p}} is not a prime,</strong> next prime is {{new_p}}, continue
        with these values? {%endif%}
        <br />
        According to
        <a
          target="_blank"
          href="https://en.wikipedia.org/wiki/Hasse%27s_theorem_on_elliptic_curves"
          >Hasse's Theorem</a
        >, total number of points will be between {{ lo }} and {{ hi }}
        <br />
        <br />
        <a href="/calculate/0" class="btn btn-warning" autofocus>Continue</a>
      </div>

      {%endif%}
      <div class="push"></div>
    </div>

    {% include "base/footer.html" %}

  </body>

  <script>
    input = document.getElementsByTagName("input");
    select = document.getElementById("id_opt");

    equation1 = document.getElementById("equation1");
    equation2 = document.getElementById("equation2");
    equation3 = document.getElementById("equation3");

    id_a = document.getElementById("id_a");
    id_d = document.getElementById("id_d");
    id_p = document.getElementById("id_p");

    displayLabels = () => {
        if (select.selectedIndex == 0) {
            equation1.style.display = "block";
            equation2.style.display = "none";
            equation3.style.display = "none";
            id_a.labels[0].innerHTML = "a";
            id_d.labels[0].innerHTML = "d";
            id_p.labels[0].innerHTML = "p";
        } 
        else if (select.selectedIndex == 1) {
            equation1.style.display = "none";
            equation2.style.display = "block";
            equation3.style.display = "none";
            id_a.labels[0].innerHTML = "a";
            id_d.labels[0].innerHTML = "d";
            id_p.labels[0].innerHTML = "p";
        } 
        else if (select.selectedIndex == 2) {
            equation1.style.display = "none";
            equation2.style.display = "none";
            equation3.style.display = "block";
            id_a.labels[0].innerHTML = "A";
            id_d.labels[0].innerHTML = "B";
            id_p.labels[0].innerHTML = "p";
        }
    }

    window.addEventListener("load", displayLabels);
    select.addEventListener("change", displayLabels);

    for (let i = 0; i < input.length; i++) {
      input[i].classList.add("form-control");
    }

    /*
    apply bootstrap to select inputs
    for (let i = 0; i < select.length; i++) {
      select[i].classList.add("form-control");
    }
    */

    // popover
    var popoverTriggerList = [].slice.call(
      document.querySelectorAll('[data-bs-toggle="popover"]')
    );
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
      return new bootstrap.Popover(popoverTriggerEl);
    });
  </script>
</html>

templates/base/notset.html
<html>
  <head>
    <title>Elliptic Calculator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
    />

    <!-- footer styles -->
    <style>
      @media only screen and (max-width: 991.5px) {
        footer {
          font-size: small;
        }
      }
      @media only screen and (max-width: 456px) {
        footer {
          font-size: 0.7em;
        }
      }
      @media only screen and (max-width: 380px) {
        footer {
          font-size: 0.6em;
        }
      }

      html,
      body {
        height: 100%;
        margin: 0;
      }
      .wrapper {
        min-height: 100%;

        /* Equal to height of footer */
        /* But also accounting for potential margin-bottom of last child */
        margin-bottom: -230px;
      }
      .footer_css_tricks,
      .push {
        height: 260px;
      }

      hr {
        border: 0;
        height: 1px;
        background-image: linear-gradient(
          to right,
          rgba(0, 0, 0, 0),
          rgba(0, 0, 0, 0.75),
          rgba(0, 0, 0, 0)
        );
      }
    </style>

    <!-- Bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script async src="/cdn-cgi/bm/cv/669835187/api.js"></script>
  </head>
  <body class="bg-light">
    <div class="container bg-white py-3 shadow rounded wrapper">
      <h1 class="text-center">Elliptic Calculator over Finite Field</h1>
      <p>Enter values for a, d and p <a href="/">here</a> first</p>
      <div class="push"></div>
    </div>

    <footer class="footer_css_tricks">
      <div class="container text-center fst-italic">
        <hr class="mb-xl-5" />
        <span class="text-muted">UG Final Year Project Work @2022 </span>
        <!-- <br /> -->
        <span class="text-muted"
          >Jadavpur University, Department of Information Technology,
          Kolkata</span
        >
        <br />
        <span class="text-muted">Developed By : </span>
        <br />
        <span class="text-muted">
          [Twisted Edwards Curve Implementation, Web Interface] : Aditya Saha
          <a href="mailto: adityacont@gmail.com">adityacont@gmail.com</a> & Ayan
          Ghosal
          <a href="mailto: ayan.ghosal007@gmail.com"
            >ayan.ghosal007@gmail.com</a
          >
        </span>
        <br />
        <span class="text-muted">
          [Short Weirstrass Curve Implementation] : Gargi Ghosal
          <a href="mailto: ghosalgargi762@gmail.com"
            >ghosalgargi762@gmail.com</a
          >
          & Agni Saha
          <a href="mailto: agnisaha7799@gmail.com">agnisaha7799@gmail.com</a>
        </span>
        <br />
        <span class="text-muted"
          >Under the guidance of Prof. Utpal Kumar Ray
          <a href="mailto: utpal.ray@jadavpuruniversity.in"
            >utpal.ray@jadavpuruniversity.in</a
          >
          <!-- <br /> -->
          , Mentorship of Mr Sujay Kumar Paul
          <a href="mailto: sujaykumarpaul@gmail.com"
            >sujaykumarpaul@gmail.com</a
          >
        </span>
      </div>
    </footer>
  </body>
</html>